const pA = new Promise((resolve, reject) => {
    //Hace algo
    resolve("Valor de A")
    //reject("Error en A")
})

pA  // => resolvi贸 a "Valor de A"
    .then() // => pB => resolvi贸 a "Valor de A"
    .then() // => pC => resolvi贸 a "Valor de A"
    .then(data => console.log(data)); // => pD => resolvi贸 a "Valor de A"
//pA.then(data => console.log(data));

//pA.then(null, (err) => console.log(err));  //aca estoy haciendo lo mismo que en la linea de abajo
//pA.catch((err) => console.log(err));
